packages:
  - '.'

allowBuilds:
  dtrace-provider: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@expo/cli@55.0.36'
  - '@expo/config@55.0.21'
  - '@expo/image-utils@0.8.17'
  - '@expo/local-build-cache-provider@55.0.16'
  - '@expo/metro-config@55.0.27'
  - '@expo/prebuild-config@55.0.22'
  - '@expo/require-utils@55.0.8'
  - babel-preset-expo@55.0.25
  - expo-asset@55.0.20
  - expo-file-system@55.0.26
  - expo-modules-autolinking@55.0.27
  - expo@55.0.30
  - expo-blur@55.0.18
  - expo-build-properties@55.0.18
  - expo-crypto@55.0.19
  - expo-dev-client@55.0.39
  - expo-dev-launcher@55.0.40
  - expo-dev-menu@55.0.34
  - expo-local-authentication@55.0.18
  - expo-manifests@55.0.21
  - expo-secure-store@55.0.18
  - expo-splash-screen@55.0.25
  - expo-system-ui@55.0.22

overrides:
  glob: ^13.0.0
  inflight: ^1.0.6
  rimraf: ^5.0.0
  text-encoding: ^0.7.0
  uuid: ^9.0.0
